# frozen_string_literal: true

source "https://rubygems.org"

gem "rbs"
gem "rubocop", require: false
gem "rubocop-shopify", require: false

gem "parallel", "~> 1.23"

gem "debug", "~> 1.8"

gem "colorize", "~> 1.1"

gem "algorithms", "~> 1.0"
